#!/usr/bin/env bash
set -u

usage() {
  cat <<'EOF'
Usage:
  compare_cupdlpx_modes.sh MODEL [options]

Options:
  --highs PATH          HiGHS executable. Default: ./bin/highs
  --out-dir DIR         Output directory. Default: ./compare_cupdlpx_logs
  --base-options FILE   Common options copied before mode-specific overrides
  --time-limit SEC      Append time_limit to all generated option files
  --mip-gap VALUE       Append mip_rel_gap to all generated option files
  --extra "TEXT"        Append raw option text to all generated option files
  --help                Show this help

Runs three modes:
  cpu                  mip_lp_solver=simplex
  cupdlpx              mip_lp_solver=pdlp, pdlp_use_cupdlpx=true
  cupdlpx_crossover    same as cupdlpx, plus pdlp_run_crossover=true
EOF
}

MODEL=""
HIGHS="./bin/highs"
OUT_DIR="./compare_cupdlpx_logs"
BASE_OPTIONS=""
TIME_LIMIT=""
MIP_GAP=""
EXTRA_OPTIONS=""

while [[ $# -gt 0 ]]; do
  case "$1" in
    --highs)
      HIGHS="$2"
      shift 2
      ;;
    --out-dir)
      OUT_DIR="$2"
      shift 2
      ;;
    --base-options)
      BASE_OPTIONS="$2"
      shift 2
      ;;
    --time-limit)
      TIME_LIMIT="$2"
      shift 2
      ;;
    --mip-gap)
      MIP_GAP="$2"
      shift 2
      ;;
    --extra)
      EXTRA_OPTIONS="${EXTRA_OPTIONS}"$'\n'"$2"
      shift 2
      ;;
    --help|-h)
      usage
      exit 0
      ;;
    -*)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 2
      ;;
    *)
      if [[ -n "$MODEL" ]]; then
        echo "Only one MODEL argument is allowed" >&2
        exit 2
      fi
      MODEL="$1"
      shift
      ;;
  esac
done

if [[ -z "$MODEL" ]]; then
  usage >&2
  exit 2
fi

if [[ ! -x "$HIGHS" ]]; then
  echo "HiGHS executable not found or not executable: $HIGHS" >&2
  exit 2
fi

if [[ ! -f "$MODEL" ]]; then
  echo "Model file not found: $MODEL" >&2
  exit 2
fi

if [[ -n "$BASE_OPTIONS" && ! -f "$BASE_OPTIONS" ]]; then
  echo "Base options file not found: $BASE_OPTIONS" >&2
  exit 2
fi

mkdir -p "$OUT_DIR"
SUMMARY="$OUT_DIR/summary.tsv"
SUMMARY_MD="$OUT_DIR/summary.md"

write_options() {
  local file="$1"
  local mode="$2"

  {
    if [[ -n "$BASE_OPTIONS" ]]; then
      cat "$BASE_OPTIONS"
      echo
    fi

    echo "# Generated by compare_cupdlpx_modes.sh"
    echo "output_flag = true"

    if [[ -n "$TIME_LIMIT" ]]; then
      echo "time_limit = $TIME_LIMIT"
    fi

    if [[ -n "$MIP_GAP" ]]; then
      echo "mip_rel_gap = $MIP_GAP"
    fi

    if [[ -n "$EXTRA_OPTIONS" ]]; then
      printf "%s\n" "$EXTRA_OPTIONS"
    fi

    case "$mode" in
      cpu)
        echo "mip_lp_solver = simplex"
        echo "pdlp_use_cupdlpx = false"
        echo "pdlp_run_crossover = false"
        ;;
      cupdlpx)
        echo "mip_lp_solver = pdlp"
        echo "pdlp_use_cupdlpx = true"
        echo "pdlp_run_crossover = false"
        ;;
      cupdlpx_crossover)
        echo "mip_lp_solver = pdlp"
        echo "pdlp_use_cupdlpx = true"
        echo "pdlp_run_crossover = true"
        ;;
      *)
        echo "Internal error: unknown mode $mode" >&2
        exit 2
        ;;
    esac
  } > "$file"
}

extract_first_value_after_colon() {
  local pattern="$1"
  local file="$2"
  awk -v pat="$pattern" '
    index($0, pat) {
      sub(/^.*: */, "", $0);
      print $0;
      exit;
    }
  ' "$file"
}

extract_solving_report_field() {
  local field="$1"
  local file="$2"
  awk -v field="$field" '
    /^Solving report/ {in_report=1; next}
    in_report && index($0, field) {
      sub("^ *" field " *", "", $0);
      print $0;
      exit;
    }
  ' "$file"
}

extract_last_debug_field_from_line() {
  local pattern="$1"
  local key="$2"
  local file="$3"
  awk -v pat="$pattern" -v key="$key" '
    index($0, pat) {line=$0}
    END {
      if (line == "") exit;
      n = split(line, parts, key "=");
      if (n < 2) exit;
      split(parts[2], value, /[, ]/);
      print value[1];
    }
  ' "$file"
}

extract_last_number_line() {
  local pattern="$1"
  local file="$2"
  awk -v pat="$pattern" '
    index($0, pat) {line=$0}
    END {
      if (line == "") exit;
      print line;
    }
  ' "$file"
}

run_mode() {
  local mode="$1"
  local opt="$OUT_DIR/${mode}.options"
  local log="$OUT_DIR/${mode}.log"
  local timefile="$OUT_DIR/${mode}.time"

  write_options "$opt" "$mode"

  echo "== Running $mode =="
  echo "Options: $opt"
  echo "Log    : $log"

  local status=0
  if command -v /usr/bin/time >/dev/null 2>&1; then
    /usr/bin/time -f "%e" -o "$timefile" \
      "$HIGHS" --options_file="$opt" --model_file="$MODEL" \
      > "$log" 2>&1 || status=$?
  else
    local start end
    start=$(date +%s)
    "$HIGHS" --options_file="$opt" --model_file="$MODEL" \
      > "$log" 2>&1 || status=$?
    end=$(date +%s)
    echo "$((end - start))" > "$timefile"
  fi

  local wall
  wall=$(cat "$timefile" 2>/dev/null || true)

  local solve_status
  solve_status=$(extract_solving_report_field "Status" "$log")

  local primal_bound
  primal_bound=$(extract_solving_report_field "Primal bound" "$log")

  local dual_bound
  dual_bound=$(extract_solving_report_field "Dual bound" "$log")

  local gap
  gap=$(extract_solving_report_field "Gap" "$log")

  local nodes
  nodes=$(extract_solving_report_field "Nodes" "$log")

  local lp_iterations
  lp_iterations=$(extract_solving_report_field "LP iterations" "$log")

  local cupdlpx_status
  cupdlpx_status=$(extract_first_value_after_colon "  Status" "$log")

  local cupdlpx_iters
  cupdlpx_iters=$(extract_first_value_after_colon "  Iterations" "$log")

  local cupdlpx_solve_time
  cupdlpx_solve_time=$(extract_first_value_after_colon "  Solve time" "$log")

  local ipx_status
  ipx_status=$(extract_last_debug_field_from_line \
    "PDLP crossover summary" "ipx_status_crossover" "$log")

  local ipx_updates
  ipx_updates=$(extract_last_debug_field_from_line \
    "PDLP crossover summary" "ipx_updates_crossover" "$log")

  local basis_valid
  basis_valid=$(extract_last_debug_field_from_line \
    "PDLP crossover summary" "basis_valid" "$log")

  local last_crossover_summary
  last_crossover_summary=$(extract_last_number_line "PDLP crossover summary" "$log")

  local cleanup_status
  cleanup_status=$(extract_last_debug_field_from_line \
    "PDLP simplex cleanup summary" "call_status" "$log")

  local cleanup_model_status
  cleanup_model_status=$(extract_last_debug_field_from_line \
    "PDLP simplex cleanup summary" "model_status" "$log")

  local cleanup_iterations
  cleanup_iterations=$(extract_last_debug_field_from_line \
    "PDLP simplex cleanup summary" "simplex_iterations" "$log")

  local cleanup_time
  cleanup_time=$(extract_last_debug_field_from_line \
    "PDLP simplex cleanup summary" "cleanup_time" "$log")

  local cleanup_basis_valid
  cleanup_basis_valid=$(extract_last_debug_field_from_line \
    "PDLP simplex cleanup summary" "basis_valid" "$log")

  local last_cleanup_summary
  last_cleanup_summary=$(extract_last_number_line "PDLP simplex cleanup summary" "$log")

  printf "%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\t%s\n" \
    "$mode" "$status" "$wall" "$solve_status" "$primal_bound" "$dual_bound" \
    "$gap" "$nodes" "$lp_iterations" "$cupdlpx_status" "$cupdlpx_iters" \
    "$cupdlpx_solve_time" "$ipx_status" "$ipx_updates" "$basis_valid" \
    "$cleanup_status" "$cleanup_model_status" "$cleanup_iterations" \
    "$cleanup_time" "$cleanup_basis_valid" \
    >> "$SUMMARY"

  {
    echo
    echo "### $mode"
    echo
    echo "- exit_status: $status"
    echo "- wall_time_sec: ${wall:-n/a}"
    echo "- solve_status: ${solve_status:-n/a}"
    echo "- primal_bound: ${primal_bound:-n/a}"
    echo "- dual_bound: ${dual_bound:-n/a}"
    echo "- gap: ${gap:-n/a}"
    echo "- nodes: ${nodes:-n/a}"
    echo "- lp_iterations: ${lp_iterations:-n/a}"
    echo "- cupdlpx_status: ${cupdlpx_status:-n/a}"
    echo "- cupdlpx_iterations: ${cupdlpx_iters:-n/a}"
    echo "- cupdlpx_solve_time: ${cupdlpx_solve_time:-n/a}"
    echo "- ipx_status_crossover: ${ipx_status:-n/a}"
    echo "- ipx_updates_crossover: ${ipx_updates:-n/a}"
    echo "- basis_valid: ${basis_valid:-n/a}"
    echo "- last_crossover_summary: ${last_crossover_summary:-n/a}"
    echo "- cleanup_call_status: ${cleanup_status:-n/a}"
    echo "- cleanup_model_status: ${cleanup_model_status:-n/a}"
    echo "- cleanup_simplex_iterations: ${cleanup_iterations:-n/a}"
    echo "- cleanup_time: ${cleanup_time:-n/a}"
    echo "- cleanup_basis_valid: ${cleanup_basis_valid:-n/a}"
    echo "- last_cleanup_summary: ${last_cleanup_summary:-n/a}"
    echo "- log: $log"
  } >> "$SUMMARY_MD"

  if [[ "$status" -ne 0 ]]; then
    echo "Mode $mode exited with status $status. Continuing." >&2
  fi
}

cat > "$SUMMARY" <<'EOF'
mode	exit_status	wall_time_sec	solve_status	primal_bound	dual_bound	gap	nodes	lp_iterations	cupdlpx_status	cupdlpx_iterations	cupdlpx_solve_time	ipx_status_crossover	ipx_updates_crossover	basis_valid	cleanup_call_status	cleanup_model_status	cleanup_simplex_iterations	cleanup_time	cleanup_basis_valid
EOF

{
  echo "# cuPDLPx mode comparison"
  echo
  echo "- model: $MODEL"
  echo "- highs: $HIGHS"
  echo "- output_dir: $OUT_DIR"
  if [[ -n "$BASE_OPTIONS" ]]; then
    echo "- base_options: $BASE_OPTIONS"
  fi
} > "$SUMMARY_MD"

run_mode cpu
run_mode cupdlpx
run_mode cupdlpx_crossover

echo
echo "Comparison finished."
echo "TSV summary : $SUMMARY"
echo "Markdown    : $SUMMARY_MD"
echo "Full logs   : $OUT_DIR/*.log"
